___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___

<img src=https://i.ibb.co/8NdjfdZ/Num-Py-logo.png width="700" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:150%; text-align:center; border-radius:10px 10px;">Numpy Arrays - Part - 02</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [IMPORTING LIBRARIES NEEDED IN THIS NOTEBOOK](#0)
* [CONCATENATION OF THE ARRAYS](#00)
    * [2D Matrix](#00.1)
* [SPLITTING OF THE ARRAYS](#000)
    * [2D Matrix](#000.1)
* [SORTING OF THE ARRAYS](#0000)
    * [2D Matrix](#0000.1)
* [NUMPY INDEXING & SELECTION](#1)
    * [Bracket Indexing & Selection](#1.1)
    * [Indexing a 2D Array (Matrices)](#1.2)
    * [Slicing a 2D Array (Matrices)](#1.3)
    * [Fancy Indexing](#1.4)
    * [Using Basic Index & Fancy Index Together](#1.5)
    * [Using Basic Slicing & Fancy Index Together](#1.6)
    * [More Indexing Help](#1.7)
* [SELECTION ON A CONDITION](#2)
* [BROADCASTING](#3)
* [NUMPY OPERATIONS](#4)
    * [Arithmetic Operations](#4.1)
    * [Universal Array Functions](#4.2)
    * [Statistical Calculations](#4.3)
* [OFFICIAL TUTORIAL](#5)
* [THE END OF THE SESSION-02](#6)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Importing Libraries Needed in This Notebook</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Once you've installed NumPy you can import it as a library:

**``NOTE:``** For installation instructions, please refer to the notebook at SESSION-01 (Numpy Part-01)

In [1]:
import numpy as np

In [4]:
a3 = np.arange(10, 30).reshape(4,5)
a3 

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [5]:
a3[1:, 2:4]

array([[17, 18],
       [22, 23],
       [27, 28]])

In [6]:
a = np.arange(20, 30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [8]:
a_slice = a[:5]
a_slice

array([20, 21, 22, 23, 24])

In [10]:
a_slice[:3] = 5 

In [11]:
a_slice

array([ 5,  5,  5, 23, 24])

In [12]:
a

array([ 5,  5,  5, 23, 24, 25, 26, 27, 28, 29])

In [13]:
a = np.arange(20, 30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
a_copy = a.copy()
a_copy

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
a_slice = a_copy[:5]
a_slice

array([20, 21, 22, 23, 24])

In [16]:
a_slice[:3] = 5
a_slice

array([ 5,  5,  5, 23, 24])

In [17]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

**REMINDER**<br>
NumPy or Numeric Python is a package for computation on homogenous n-dimensional arrays. In numpy dimensions are called as axes.

**Why do we need NumPy?**

A question arises that why do we need NumPy when python lists are already there. The answer to it is we cannot perform operations on all the elements of two list directly. For example, we cannot multiply two lists directly we will have to do it element-wise. This is where the role of NumPy comes into play.

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Concatenation of the Arrays</p>

<a id="00"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In this lecture we will first discuss how to concatenate, split and sort the arrays.

**``concatenate((a1, a2, ...), axis=0, out=None)``**

In [18]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])

In [19]:
np.concatenate((x, y))

array([1, 2, 3, 4, 5, 6])

In [20]:
np.concatenate((x, y, z))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.concatenate((x, y, z), axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [22]:
x

array([1, 2, 3])

In [23]:
x.reshape(1, 3)

array([[1, 2, 3]])

In [24]:
np.concatenate([x.reshape(1, 3), y.reshape(1, 3), z.reshape(1, 3)], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.concatenate([x.reshape(1, 3), y.reshape(1, 3), z.reshape(1, 3)], axis = 1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">2d Matrix</p>

<a id="00.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [29]:
a = np.random.randint(10, size = (2, 3))
b = np.random.randint(10, size = (2, 3))

In [30]:
a

array([[6, 7, 5],
       [9, 3, 6]])

In [31]:
b

array([[1, 9, 4],
       [4, 7, 8]])

In [33]:
a, b

(array([[6, 7, 5],
        [9, 3, 6]]),
 array([[1, 9, 4],
        [4, 7, 8]]))

In [34]:
np.concatenate( (a,b), axis=0 )

array([[6, 7, 5],
       [9, 3, 6],
       [1, 9, 4],
       [4, 7, 8]])

In [35]:
np.concatenate( (a,b), axis=1 )

array([[6, 7, 5, 1, 9, 4],
       [9, 3, 6, 4, 7, 8]])

In [36]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
y = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
y

array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [38]:
np.concatenate([x,y], axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [39]:
np.concatenate([x,y], axis = 1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Splitting of the Arrays</p>

<a id="000"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**``np.split(ary, indices_or_sections, axis=0)``**

In [40]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [41]:
np.split(x, [3, 5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [42]:
len(np.split(x, [3, 5]))

3

In [43]:
a, b, c = np.split(x, [3, 5])

In [44]:
a

array([1, 2, 3])

In [45]:
b

array([99, 99])

In [46]:
c

array([3, 2, 1])

In [47]:
np.split(x, [4])

[array([ 1,  2,  3, 99]), array([99,  3,  2,  1])]

In [48]:
np.split(x, 4)

[array([1, 2]), array([ 3, 99]), array([99,  3]), array([2, 1])]

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">2d Matrix</p>

<a id="000.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [50]:
m = np.arange(20).reshape(5, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [51]:
np.split(m, [1, 3], axis = 0)

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [52]:
np.split(m, [1, 3], axis = 1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [53]:
np.vsplit(m, [1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [54]:
np.vsplit(m, [3])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [55]:
upper, lower = np.vsplit(m, [3])

In [56]:
upper


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
lower

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [59]:
np.vsplit(m, 5)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [61]:
left, right = np.hsplit(m, [2])

In [62]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [63]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Sorting of the Arrays</p>

<a id="0000"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [64]:
v = np.array([2, 1, 4, 3, 5])
v

array([2, 1, 4, 3, 5])

In [65]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [66]:
v

array([2, 1, 4, 3, 5])

In [67]:
v.sort()

In [68]:
v

array([1, 2, 3, 4, 5])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">2d Matrix</p>

<a id="0000.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [69]:
twoD = np.random.randint(5, 100, (3, 3))
twoD

array([[58, 57, 56],
       [70, 49, 93],
       [ 5, 53, 33]])

In [70]:
np.sort(twoD, axis = 0)

array([[ 5, 49, 33],
       [58, 53, 56],
       [70, 57, 93]])

In [72]:
twoD

array([[58, 57, 56],
       [70, 49, 93],
       [ 5, 53, 33]])

In [71]:
np.sort(twoD, axis = 1)

array([[56, 57, 58],
       [49, 70, 93],
       [ 5, 33, 53]])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Indexing & Selection</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In this part of the lecture we will discuss how to select elements or groups of elements from an array.

Array indexing is the same as accessing an array element. You can access an array element by referring to its index number. The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc. [SOURCE](https://www.w3schools.com/python/numpy/numpy_array_indexing.asp)

### ``Types of Indexing``

There are **``two types of indexing:``**

**``1 - Basic Slicing and indexing:``** Consider the syntax x[obj] where x is the array and obj is the index. Slice object is the index in case of basic slicing. Basic slicing occurs when obj is :
- a slice object that is of the form start : stop : step
- an integer
- or a tuple of slice objects and integers

**``2 - Advanced indexing:``** Advanced indexing is triggered when obj is –

- an ndarray of type integer or Boolean
- or a tuple with at least one sequence object
- is a non tuple sequence object

For more information, please visit [INDEXING SOURCE](https://www.geeksforgeeks.org/numpy-indexing/)


[INDEXING & SLICING Source 01](https://jakevdp.github.io/PythonDataScienceHandbook/03.02-data-indexing-and-selection.html),
[INDEXING & SLICING Source 02](https://www.kite.com/python/answers/how-to-select-an-element-by-index-from-a-numpy-array-in-python),
[INDEXING & SLICING Source 03](https://numpy.org/doc/stable/reference/arrays.indexing.html),
[INDEXING & SLICING Source 04](https://www.pluralsight.com/guides/working-numpy-arrays-indexing-slicing-guide),
[INDEXING & SLICING Source 05](https://www.brainstobytes.com/hands-on-numpy-iii-indexing-and-slicing/),
[INDEXING & SLICING Source 06](https://pandas.pydata.org/pandas-docs/version/1.2.4/user_guide/indexing.html),
[INDEXING & SLICING Source 07](https://www.tutorialspoint.com/numpy/numpy_advanced_indexing.htm),
[INDEXING & SLICING Source 08](https://towardsdatascience.com/numpy-indexing-explained-c376abb2440d),
[INDEXING & SLICING Video Source 01](https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/),
[INDEXING & SLICING Video Source 02](https://www.youtube.com/watch?v=9nbBTaz2qXI),
[INDEXING & SLICING Video Source 03](https://www.youtube.com/watch?v=9nbBTaz2qXI) &
[INDEXING & SLICING Video Source 03](https://www.youtube.com/watch?v=E1OFcMnU40o)

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Bracket Indexing & Selection</p>

<a id="1.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

The simplest way to pick one or some elements of an array looks very similar to python lists:

In [73]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr[8]

8

In [75]:
arr[-3]

8

In [76]:
arr[:5]

array([0, 1, 2, 3, 4])

In [77]:
arr[0::2]

array([ 0,  2,  4,  6,  8, 10])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Indexing a 2D Array (Matrices)</p>

<a id="1.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

<p>The general format is <b>arr_2d[row][col]</b> or <b>arr_2d[row, col]</b>.<br> 
It's usually recommended using the comma notation for clarity.</p>

![image.png](https://i.ibb.co/pvdHbBm/numpy-index.png)

![image-2.png](https://i.ibb.co/jJPp6hk/numpy-indexing2.png)

[SOURCE01](https://www.google.com/url?sa=i&url=https%3A%2F%2Fmedium.com%2F%40msjahid%2Fnumpy-array-indexing-slicing-23b70abb8433&psig=AOvVaw2ETiXFpQ-F-d0CMV8jD1dJ&ust=1644053862804000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCIDj5JXg5fUCFQAAAAAdAAAAABAk), [SOURCE02](https://www.google.com/url?sa=i&url=https%3A%2F%2Fiq.opengenus.org%2F2d-array-in-numpy%2F&psig=AOvVaw2ETiXFpQ-F-d0CMV8jD1dJ&ust=1644053862804000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCIDj5JXg5fUCFQAAAAAdAAAAABAp)<br>

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Slicing a 2D Array (Matrices)</p>

<a id="1.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

If you know how to select subsets of Python lists, you know most of what you need to know about ndarray slicing. The elements of the array being indexed that correspond to the elements of the indexing object are returned in a new array. The most important aspect of indexing is to remember that there is more than one dimension, and the indexing method should be able to handle these other dimensions.

![image-2.png](https://i.ibb.co/64DGhj7/Numpy-index.jpg)

[SOURCE](https://www.google.com/url?sa=i&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F16096753%2Fpython-array-slicing-how-can-2d-array-slicing-be-implemented&psig=AOvVaw0cHqeY-itYpRm19imsEBuR&ust=1644054927553000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCNiUt4vk5fUCFQAAAAAdAAAAABAD)

In [78]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [79]:
arr_2d[1]

array([20, 25, 30])

In [80]:
arr_2d[1, 1]

25

In [82]:
type(arr_2d[1, 1])

numpy.int32

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Fancy Indexing</p>

<a id="1.4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Fancy indexing is conceptually simple: it means passing an array of indices to access multiple array elements at once [SOURCE](https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html#:~:text=Fancy%20indexing%20is%20conceptually%20simple,random.). In Fancy Indexing, we pass array of indices instead of single scalar(numbers) to fetch elements at different index points. Remember that the shape of the output depends on the shape of the index arrays rather than the shape of the array being indexed. [SOURCE01](https://www.google.com/url?sa=i&url=https%3A%2F%2Ftahamaddam.com%2Fcoding%2Fnumpy%2Fnumpy-fancy-indexing%2F&psig=AOvVaw3D06ReHkWL4NNeBSEHNddn&ust=1644055555472000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCPDY4bTm5fUCFQAAAAAdAAAAABAD), [SOURCE02](https://www.google.com/url?sa=i&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F52485840%2Fnumpy-fancy-indexing-with-tuples%3Frq%3D1&psig=AOvVaw3D06ReHkWL4NNeBSEHNddn&ust=1644055555472000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCPDY4bTm5fUCFQAAAAAdAAAAABAO), [VIDEO SOURCE](https://www.youtube.com/watch?v=WpXH4PzDtYA)

Fancy indexing allows you to select entire rows or columns out of order, to show this, let's quickly build out a numpy array:

In [83]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [84]:
v[1]

3

In [85]:
v[3]

9

In [86]:
v[5]

15

In [87]:
v[[1,3,5]]

array([ 3,  9, 15])

In [88]:
arr2d = np.zeros((10, 10), dtype=int)
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [91]:
lenght_rows = arr2d.shape[0]
lenght_rows

10

In [93]:
for i in range(lenght_rows):
    arr2d[i] = i 
    
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [94]:
arr2d[3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [96]:
arr2d[[6, 4, 2, 7]]

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

<h3>any_array[[row indices], [column indices]]</h3>

In [97]:
jj = np.arange(1, 17)
jj

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [99]:
jj = jj.reshape(4,4)
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [100]:
jj[1, 0]

5

In [101]:
jj[2, 3]

12

In [102]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [103]:
jj[[1, 2], [0, 3]]

array([ 5, 12])

In [106]:
jj[[1, 2, 0], [0, 3]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [107]:
jj[[1, 2, 0], [1, 0, 3]]

array([6, 9, 4])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Using ***Basic Index*** & ***Fancy Index*** Together</p>

<a id="1.5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>



In [108]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [109]:
jj[[1,1], [1,3]]

array([6, 8])

In [110]:
jj[1, [1,3]]

array([6, 8])

In [111]:
jj[[1], [1,3]]

array([6, 8])

In [112]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [113]:
jj[[1,3], 1]

array([ 6, 14])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Using ***Basic Slicing*** & ***Fancy Index*** Together</p>

<a id="1.6"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>


In [114]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [115]:
jj[:, [1, 2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [117]:
jj[1:3, [1, 3]]

array([[ 6,  8],
       [10, 12]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">More Indexing Help</p>

<a id="1.7"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>


Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images.

![image.png](https://i.ibb.co/xmcGm9C/numpy-index1.png)

[SOURCE](https://www.google.com/url?sa=i&url=https%3A%2F%2Fscipy-lectures.org%2Fintro%2Fnumpy%2Farray_object.html&psig=AOvVaw21eb1iMrmWndUhejWXLkY-&ust=1644056657663000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCICAqr_q5fUCFQAAAAAdAAAAABAD)

Numpy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called fancy indexing. It creates copies not views. [SOURCE](http://cs-tklab.na-inet.jp/~tkouya/python/scipy-lectures/intro/numpy/array_object.html)

![image-2.png](https://i.ibb.co/bHYsGLb/numpy-indexing-1.png)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Selection on a Condition</p>

<a id="2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [118]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
condition = arr > 4

In [121]:
condition

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [122]:
arr[condition]

array([ 5,  6,  7,  8,  9, 10])

In [124]:
(arr != 3) & (arr != 4)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [125]:
arr[(arr != 3) & (arr != 4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

In [126]:
arr[(((arr < 3) | (arr > 8)) & ((arr !=9) & (arr != 2)))]

array([ 1, 10])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Broadcasting</p>

<a id="3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Numpy arrays differ from a normal Python list because of their ability to broadcast [SOURCE](https://numpy.org/doc/stable/user/theory.broadcasting.html).<br>

**``Broadcasting``** is the name given to the method that NumPy uses to allow array arithmetic between arrays with a different shape or size [SOURCE](https://machinelearningmastery.com/broadcasting-with-numpy-arrays/#:~:text=Broadcasting%20is%20the%20name%20given,a%20different%20shape%20or%20size.&text=Subject%20to%20certain%20constraints%2C%20the,that%20they%20have%20compatible%20shapes.).<br>

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is **``broadcast``** across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation [SOURCE](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html).<br> 

Broadcasting is an operation of matching the dimensions of differently shaped arrays in order to be able to perform further operations on those arrays (eg per-element aritmetic) [SOURCE01](https://towardsdatascience.com/broadcasting-in-numpy-58856f926d73), [SOURCE02](https://towardsdatascience.com/a-numpy-affair-broadcasting-ead20d9661f).<br>

**NumPy Broadcasting Limitations**<br>
Broadcasting is a very easy and handy tool when working with Numpy arrays. Although, there are many rules and restrictions to perform the operations.

There are constraints on the dimension and shape of the arrays. We can perform broadcasting in cases where both the arrays have the same shape or only if either of the two has a size of 1. Also, we have to consider the dimensions in reverse order. We count it from the trailing dimension [SOURCE](https://data-flair.training/blogs/numpy-broadcasting/).<br>

Be informed about the discussion on [When broadcasting is a bad idea? (numpy)](https://stackoverflow.com/questions/47309818/when-broadcasting-is-a-bad-idea-numpy) at Stackoverflow.

More Sources: [SOURCE01](https://inblog.in/Broadcasting-in-Numpy-A-Complete-Guide-jfKy2vzHiY), [SOURCE02](https://www.pluralsight.com/guides/broadcasting-numpy-arrays-arithmeetic-operations), [SOURCE03](https://www.geeksforgeeks.org/python-broadcasting-with-numpy-arrays/), [SOURCE04](https://www.askpython.com/python-modules/numpy/numpy-broadcasting), [SOURCE05](https://stackoverflow.com/questions/32832923/numpy-what-is-broadcasting), [SOURCE06](https://stackoverflow.com/questions/61090539/how-can-i-use-broadcasting-with-numpy-to-speed-up-this-correlation-calculation), [SOURCE07](https://stackoverflow.com/questions/68185016/numpy-broadcasting-two-arrays-of-different-shape-to-matrix), [SOURCE08](https://stackoverflow.com/questions/50569344/broadcasting-using-numpys-sum-function)

In [127]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
a = [0, 2, 4 ,6, 8 ,10]
a

[0, 2, 4, 6, 8, 10]

In [129]:
a[:3] = 100

TypeError: can only assign an iterable

In [130]:
a[:3] = 100, 100, 100

In [131]:
a

[100, 100, 100, 6, 8, 10]

In [133]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [135]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [136]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [137]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [138]:
arr_copy[:6] = [0, 1, 2, 3, 4, 5]
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [139]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Operations</p>

<a id="4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

![image.png](https://i.ibb.co/n65mpTL/numpy-operations.png)

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Arithmetic Operations</p>

<a id="4.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

#### You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [140]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [142]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [143]:
arr / arr

C:\Users\edwin\AppData\Local\Temp\ipykernel_15192\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [145]:
import warnings
warnings.filterwarnings('ignore')

In [146]:
arr / arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [147]:
1 / arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [148]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [150]:
np.subtract(arr, 1)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [170]:
np.add(arr, 2)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [151]:
np.multiply(arr, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [171]:
np.divide(arr, 2)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [172]:
np.power(arr,3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [173]:
np.mod(arr,2)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [174]:
np.mod(arr[arr>3], 2)

array([0, 1, 0, 1, 0, 1], dtype=int32)

In [175]:
np.absolute(-9)

9

In [176]:
np.absolute([-3,-5,4,6])

array([3, 5, 4, 6])

In [177]:
np.add([1,2,3], 10)

array([11, 12, 13])

In [152]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [168]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [169]:
arr*1/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [178]:
x1 = np.arange(9.0).reshape(3, 3)
x2 = np.arange(3.0)

In [179]:
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [180]:
x2

array([0., 1., 2.])

In [181]:
np.subtract(x1, x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Universal Array Functions</p>

#### Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [153]:
print(type(np.add))

<class 'numpy.ufunc'>


In [154]:
print(type(np.concatenate))

<class 'function'>


In [155]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [156]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [182]:
np.max(arr)

9

In [183]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [184]:
np.sin(np.pi/2)

1.0

In [185]:
np.tan(np.pi/4)

0.9999999999999999

In [186]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [187]:
np.log10(1000)

3.0

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Statistical Calculations</p>

<a id="4.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Statistics is concerned with collecting and then analyzing that data. It includes methods for collecting the samples, describing the data, and then concluding that data. NumPy is the fundamental package for scientific calculations and hence goes hand-in-hand for NumPy statistical Functions.

NumPy contains various statistical functions that are used to perform statistical data analysis. These statistical functions are useful when finding a maximum or minimum of elements. It is also used to find basic statistical concepts like standard deviation, variance, etc.

NumPy is equipped with the following statistical functions:

**``np.amin(arr)``** This function determines the minimum value of the element along a specified axis.<br>
**``np.amax(arr)``** This function determines the maximum value of the element along a specified axis.<br>
**``arr.min()``** Returns minimum value of arr<br>
**``arr.max(axis=0)``** Returns maximum value of specific axis<br>
**``np.mean(arr, axis=0)``** It determines the mean value of the data set.<br>
**``np.median(arr)``** It determines the median value of the data set.<br>
**``np.std(arr, axis=1)``** It determines the standard deviation.<br>
**``np.var(arr)``** It determines the variance.<br>
**``np.ptp(arr)``** It returns a range of values (maximum - minimum) along an axis.<br>
**``np.average(arr)``** It determines the weighted average.<br>
**``np.percentile(arr)``** It determines the nth percentile of data along the specified axis.<br>
**``np.corrcoef(arr)``** Returns correlation coefficient of array

More Sources: [SOURCE01](https://data-flair.training/blogs/numpy-statistical-functions/), [SOURCE02](https://python-tricks.com/statistical-functions-in-numpy/), [SOURCE03](https://numpy.org/doc/stable/reference/routines.statistics.html), [SOURCE04](https://www.tutorialspoint.com/numpy/numpy_statistical_functions.htm), [SOURCE05](https://www.i2tutorials.com/numpy-tutorial/numpy-statistical-functions/), [SOURCE06](https://towardsdatascience.com/use-numpy-for-statistics-and-arithmetic-operations-in-2020-2e157b784df4), [SOURCE07](https://cloudxlab.com/assessment/displayslide/2509/numpy-mathematical-and-statistical-functions-on-numpy-arrays), [SOURCE08](https://stackoverflow.com/questions/63888139/calculating-some-statistics-for-each-column-of-a-numpy-ndarray), [SOURCE09](https://www.codecademy.com/learn/intro-statistics-numpy)

In [158]:
v = np.array([1, 1, 2, 2, 3, 3, 3])
v

array([1, 1, 2, 2, 3, 3, 3])

In [159]:
np.mean(v)

2.142857142857143

In [160]:
v.mean()

2.142857142857143

In [161]:
arry = np.array([4,7,1,9,1,2,6,8])

arry = np.sort(arry)
arry

array([1, 1, 2, 4, 6, 7, 8, 9])

In [162]:
np.median(arry)

5.0

In [163]:
v.var()

0.6938775510204082

In [164]:
v.std()

0.8329931278350429

In [188]:
v.sum()

15

In [189]:
v.min()

1

In [190]:
np.ptp(v) # peak to peak 

2

In [191]:
import numpy as np

arr = np.random.randint(0, 100, size=(3, 4))
print("Dizi:")
print(arr)

ptp_axis0 = np.ptp(arr, axis=0)
ptp_axis1 = np.ptp(arr, axis=1)

print("Eksende Peak to Peak Değerleri:")
print("Eksen 0:", ptp_axis0)
print("Eksen 1:", ptp_axis1)
ptp_total = np.ptp(arr)

print("Toplam Peak to Peak Değeri:", ptp_total)

Dizi:
[[58 41 91 59]
 [79 14 61 61]
 [46 61 50 54]]
Eksende Peak to Peak Değerleri:
Eksen 0: [33 47 41  7]
Eksen 1: [50 65 15]
Toplam Peak to Peak Değeri: 77


In [165]:
np.random.seed(42)

xarr = np.random.randn(3,5)
xarr

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783]])

In [166]:
np.random.seed(42)
np.random.randn(3,5)

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783]])

In [192]:
np.corrcoef(xarr)

array([[ 1.        , -0.72342114, -0.20484812],
       [-0.72342114,  1.        ,  0.46728036],
       [-0.20484812,  0.46728036,  1.        ]])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Official Tutorial</p>

<a id="5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

## You can take a look at an attractive [official tutorial](https://numpy.org/devdocs/user/absolute_beginners.html) for beginners of NumPy.

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:150%; text-align:center; border-radius:10px 10px;">The End of the NumPy Session - 02</p>

<a id="6"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>
___